#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover
    load_dotenv = None

try:
    import psycopg
    from psycopg import sql
except ImportError as exc:  # pragma: no cover
    raise SystemExit("psycopg is required. Run: .venv/bin/python -m pip install -r requirements.txt") from exc


ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_SQLITE = ROOT_DIR / "backend" / "data" / "zhuwei.sqlite3"
DEFAULT_REPORT = ROOT_DIR / "backend" / "data" / "postgres_migration_report.json"
SQLITE_INTERNAL_TABLES = {"sqlite_sequence", "sqlite_stat1", "sqlite_stat4"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Migrate the current SQLite database into PostgreSQL without switching the app data source.",
    )
    parser.add_argument("--sqlite", default=os.getenv("DATABASE_PATH", str(DEFAULT_SQLITE)))
    parser.add_argument(
        "--postgres-url",
        default=os.getenv("POSTGRES_MIGRATION_URL") or os.getenv("DATABASE_URL") or "",
        help="PostgreSQL URL, e.g. postgresql://zhuwei:...@127.0.0.1:5432/zhuwei",
    )
    parser.add_argument("--schema", default=os.getenv("POSTGRES_SCHEMA", "public"))
    parser.add_argument("--drop-target", action="store_true", help="Drop target PostgreSQL tables before migrating.")
    parser.add_argument("--report", default=str(DEFAULT_REPORT))
    parser.add_argument("--batch-size", type=int, default=1000)
    return parser.parse_args()


def sqlite_path(value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else ROOT_DIR / path


def sqlite_tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type='table'
          AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()
    return [str(row["name"]) for row in rows if str(row["name"]) not in SQLITE_INTERNAL_TABLES]


def table_columns(conn: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    rows = conn.execute(f"PRAGMA table_info({_sqlite_ident(table)})").fetchall()
    return [dict(row) for row in rows]


def _sqlite_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def pg_type(sqlite_type: str, *, identity: bool) -> str:
    text = (sqlite_type or "").upper()
    if identity:
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY"
    if "INT" in text:
        return "BIGINT"
    if any(token in text for token in ["REAL", "FLOA", "DOUB"]):
        return "DOUBLE PRECISION"
    if "BLOB" in text:
        return "BYTEA"
    if any(token in text for token in ["NUM", "DEC", "BOOL"]):
        return "NUMERIC"
    return "TEXT"


def create_schema(pg: psycopg.Connection, schema: str) -> None:
    with pg.cursor() as cur:
        cur.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(schema)))


def drop_tables(pg: psycopg.Connection, schema: str, tables: list[str]) -> None:
    with pg.cursor() as cur:
        for table in reversed(tables):
            cur.execute(
                sql.SQL("DROP TABLE IF EXISTS {}.{} CASCADE").format(
                    sql.Identifier(schema),
                    sql.Identifier(table),
                )
            )


def create_table(pg: psycopg.Connection, schema: str, table: str, columns: list[dict[str, Any]]) -> None:
    primary_columns = [col for col in columns if int(col.get("pk") or 0) > 0]
    single_pk = primary_columns[0] if len(primary_columns) == 1 else None
    column_defs: list[sql.Composable] = []
    for col in columns:
        name = str(col["name"])
        sqlite_type = str(col.get("type") or "")
        is_single_int_pk = bool(single_pk and single_pk["name"] == name and "INT" in sqlite_type.upper())
        parts: list[sql.Composable] = [
            sql.Identifier(name),
            sql.SQL(pg_type(sqlite_type, identity=is_single_int_pk)),
        ]
        if single_pk and single_pk["name"] == name:
            parts.append(sql.SQL("PRIMARY KEY"))
        elif int(col.get("notnull") or 0):
            parts.append(sql.SQL("NOT NULL"))
        column_defs.append(sql.SQL(" ").join(parts))
    if len(primary_columns) > 1:
        ordered = sorted(primary_columns, key=lambda item: int(item.get("pk") or 0))
        column_defs.append(
            sql.SQL("PRIMARY KEY ({})").format(
                sql.SQL(", ").join(sql.Identifier(str(col["name"])) for col in ordered)
            )
        )
    with pg.cursor() as cur:
        cur.execute(
            sql.SQL("CREATE TABLE IF NOT EXISTS {}.{} ({})").format(
                sql.Identifier(schema),
                sql.Identifier(table),
                sql.SQL(", ").join(column_defs),
            )
        )


def fetch_rows(conn: sqlite3.Connection, table: str, batch_size: int) -> tuple[list[str], list[sqlite3.Row]]:
    cursor = conn.execute(f"SELECT * FROM {_sqlite_ident(table)}")
    columns = [item[0] for item in cursor.description or []]
    while True:
        rows = cursor.fetchmany(batch_size)
        if not rows:
            break
        yield columns, rows


def insert_rows(
    pg: psycopg.Connection,
    schema: str,
    table: str,
    columns: list[str],
    rows: list[sqlite3.Row],
) -> int:
    if not columns or not rows:
        return 0
    statement = sql.SQL("INSERT INTO {}.{} ({}) VALUES ({})").format(
        sql.Identifier(schema),
        sql.Identifier(table),
        sql.SQL(", ").join(sql.Identifier(col) for col in columns),
        sql.SQL(", ").join(sql.Placeholder() for _ in columns),
    )
    values = [tuple(row[col] for col in columns) for row in rows]
    with pg.cursor() as cur:
        cur.executemany(statement, values)
    return len(rows)


def reset_identity(pg: psycopg.Connection, schema: str, table: str, columns: list[dict[str, Any]]) -> None:
    primary_columns = [col for col in columns if int(col.get("pk") or 0) > 0]
    if len(primary_columns) != 1:
        return
    column = primary_columns[0]
    if "INT" not in str(column.get("type") or "").upper():
        return
    with pg.cursor() as cur:
        cur.execute(
            sql.SQL(
                """
                SELECT setval(
                    pg_get_serial_sequence(%s, %s),
                    COALESCE((SELECT MAX({column}) FROM {schema}.{table}), 1),
                    (SELECT COUNT(*) > 0 FROM {schema}.{table})
                )
                """
            ).format(
                column=sql.Identifier(str(column["name"])),
                schema=sql.Identifier(schema),
                table=sql.Identifier(table),
            ),
            (f"{schema}.{table}", str(column["name"])),
        )


def count_pg(pg: psycopg.Connection, schema: str, table: str) -> int:
    with pg.cursor() as cur:
        cur.execute(
            sql.SQL("SELECT COUNT(*) FROM {}.{}").format(
                sql.Identifier(schema),
                sql.Identifier(table),
            )
        )
        return int(cur.fetchone()[0])


def redact_url(url: str) -> str:
    return re.sub(r"://([^:/@]+):([^@]+)@", r"://\1:***@", url)


def main() -> int:
    if load_dotenv is not None:
        load_dotenv(ROOT_DIR / ".env")
    args = parse_args()
    sqlite_file = sqlite_path(args.sqlite)
    if not sqlite_file.exists():
        print(f"SQLite database not found: {sqlite_file}", file=sys.stderr)
        return 2
    if not args.postgres_url:
        print("DATABASE_URL or --postgres-url is required for migration.", file=sys.stderr)
        return 2

    report: dict[str, Any] = {
        "started_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "sqlite": str(sqlite_file),
        "postgres_url": redact_url(args.postgres_url),
        "schema": args.schema,
        "drop_target": bool(args.drop_target),
        "tables": [],
    }

    sqlite_conn = sqlite3.connect(sqlite_file)
    sqlite_conn.row_factory = sqlite3.Row
    sqlite_conn.execute("PRAGMA query_only=ON")
    tables = sqlite_tables(sqlite_conn)
    with psycopg.connect(args.postgres_url, autocommit=False) as pg:
        create_schema(pg, args.schema)
        if args.drop_target:
            drop_tables(pg, args.schema, tables)
        for table in tables:
            columns = table_columns(sqlite_conn, table)
            create_table(pg, args.schema, table, columns)
            inserted = 0
            for batch_columns, rows in fetch_rows(sqlite_conn, table, max(1, args.batch_size)):
                inserted += insert_rows(pg, args.schema, table, batch_columns, rows)
            reset_identity(pg, args.schema, table, columns)
            sqlite_count = int(sqlite_conn.execute(f"SELECT COUNT(*) AS n FROM {_sqlite_ident(table)}").fetchone()["n"])
            pg_count = count_pg(pg, args.schema, table)
            status = "ok" if sqlite_count == pg_count else "mismatch"
            report["tables"].append(
                {
                    "table": table,
                    "sqlite_count": sqlite_count,
                    "postgres_count": pg_count,
                    "inserted": inserted,
                    "status": status,
                }
            )
            print(f"{table}: sqlite={sqlite_count} postgres={pg_count} status={status}")
        report["finished_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        report["status"] = "ok" if all(item["status"] == "ok" for item in report["tables"]) else "mismatch"
        pg.commit()
    sqlite_conn.close()

    report_path = Path(args.report)
    report_path = report_path if report_path.is_absolute() else ROOT_DIR / report_path
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"migration report: {report_path}")
    return 0 if report["status"] == "ok" else 1


if __name__ == "__main__":
    raise SystemExit(main())
